ARG STORM_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${STORM_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
